from __future__ import annotations

from dataclasses import dataclass

import pytest

from flowmaticdb import QueryError
from flowmaticdb.dialects import SQLDialect
from flowmaticdb.query import AlterTableQuery, CreateTableQuery, DropTableQuery
from flowmaticdb.query.ddl import (
    AddColumn,
    AddForeignKeyConstraint,
    AddPrimaryKeys,
    AddUniqueConstraint,
    AlterABC,
    AlterColumn,
    Column,
    ConstraintABC,
    DropColumn,
    DropConstraint,
    ForeignKeyConstraint,
    RawAlter,
    RawConstraint,
    RenameColumn,
    UniqueConstraint,
)
from flowmaticdb.query.enums import ReferentialActionEnum, TypeEnum


def test_create_table_integer_threads_bits_into_dialect_type(sql_dialect: SQLDialect, mock_db) -> None:
    """CreateTableQuery.integer() dropped `bits` before reaching the column dict,
    so every int column rendered with the dialect's default size (0) instead of
    the requested one. bits=64 (the default, matching PHP) must yield BIGINT."""
    q = CreateTableQuery(sql_dialect, "widgets", database=mock_db)
    q.integer("count", bits=64)
    sql = q.to_query_with_params().query

    assert "BIGINT" in sql
    assert '"count"' in sql


def test_create_table_integer_small_bits_stays_integer(sql_dialect: SQLDialect, mock_db) -> None:
    q = CreateTableQuery(sql_dialect, "widgets", database=mock_db)
    q.integer("count", bits=32)
    sql = q.to_query_with_params().query

    assert "INTEGER" in sql
    assert "BIGINT" not in sql


def test_create_table_string_threads_size_into_dialect_type(sql_dialect: SQLDialect, mock_db) -> None:
    q = CreateTableQuery(sql_dialect, "widgets", database=mock_db)
    q.string("name", size=100)
    sql = q.to_query_with_params().query

    assert "VARCHAR(100)" in sql


def test_create_table_text_uses_big_string_type(sql_dialect: SQLDialect, mock_db) -> None:
    """PHP's text() forwards PHP_INT_MAX as the size so the dialect picks its
    "big string" type (TEXT here). The port previously passed 0, which is falsy
    and produced a bounded VARCHAR(255) instead."""
    q = CreateTableQuery(sql_dialect, "widgets", database=mock_db)
    q.text("bio")
    sql = q.to_query_with_params().query

    assert "TEXT" in sql
    assert "VARCHAR" not in sql


def test_alter_table_add_int_threads_bits(sql_dialect: SQLDialect, mock_db) -> None:
    q = AlterTableQuery(sql_dialect, "widgets", database=mock_db)
    q.add_int("count", bits=64)
    result = q.to_query_with_params()

    assert "BIGINT" in result[0].query


def test_alter_table_add_text_uses_big_string_type(sql_dialect: SQLDialect, mock_db) -> None:
    q = AlterTableQuery(sql_dialect, "widgets", database=mock_db)
    q.add_text("bio")
    result = q.to_query_with_params()

    assert "TEXT" in result[0].query
    assert "VARCHAR" not in result[0].query


def test_create_table_float_threads_bits(sql_dialect: SQLDialect, mock_db) -> None:
    q = CreateTableQuery(sql_dialect, "widgets", database=mock_db)
    q.float("score", bits=64)
    sql = q.to_query_with_params().query

    assert "DECIMAL(30, 15)" in sql


def test_create_table_date_time_threads_size(sql_dialect: SQLDialect, mock_db) -> None:
    """date_time()'s size doesn't affect the base dialect's rendering (it has
    a single DATETIME mapping) but must still reach the column dict rather
    than silently vanish."""
    q = CreateTableQuery(sql_dialect, "widgets", database=mock_db)
    q.date_time("created_at", size=3)
    col = q._columns[0]

    assert col.bits == 3

def test_create_table_identity_is_still_bigint_by_default(sql_dialect: SQLDialect, mock_db) -> None:
    q = CreateTableQuery(sql_dialect, "widgets", database=mock_db)
    q.identity("id")
    sql = q.to_query_with_params().query

    assert "BIGINT" in sql
    assert "GENERATED BY DEFAULT AS IDENTITY" in sql

def test_create_table_explain_returns_empty_list(sql_dialect: SQLDialect, mock_db) -> None:
    q = CreateTableQuery(sql_dialect, "widgets", database=mock_db)
    q.integer("id")

    assert q.explain() == []


def test_alter_table_explain_returns_empty_list_without_executing(sql_dialect: SQLDialect, mock_db) -> None:
    """The port previously delegated to the base Query.explain(), which would
    try to run EXPLAIN against the database for every alter statement."""
    q = AlterTableQuery(sql_dialect, "widgets", database=mock_db)
    q.add_column("email", "VARCHAR")

    assert q.explain() == []


def test_drop_table_explain_returns_empty_list(sql_dialect: SQLDialect, mock_db) -> None:
    q = DropTableQuery(sql_dialect, "widgets", database=mock_db)

    assert q.explain() == []

def test_create_table_raw_constraint_does_not_crash(sql_dialect: SQLDialect, mock_db) -> None:
    """constraint() previously appended a bare string, but dialects call
    `.get("type")` on every constraint entry, crashing with AttributeError."""
    q = CreateTableQuery(sql_dialect, "widgets", database=mock_db)
    q.integer("id")
    q.constraint("CHECK (id > 0)")

    q.to_query_with_params()


def test_alter_table_raw_alter_does_not_crash(sql_dialect: SQLDialect, mock_db) -> None:
    """alter() previously appended a bare string, but dialects call
    `.get("type")` on every alter entry, crashing with AttributeError."""
    q = AlterTableQuery(sql_dialect, "widgets", database=mock_db)
    q.alter("SOME RAW SQL")

    q.to_query_with_params()


def test_alter_table_alter_column_does_not_crash(sql_dialect: SQLDialect, mock_db) -> None:
    """alter_column() previously stored the column name as a bare string under
    "column", but the dialect's alter_column handling calls `.get("name")` on
    it, crashing with AttributeError."""
    q = AlterTableQuery(sql_dialect, "widgets", database=mock_db)
    q.alter_column("age", "TYPE INTEGER")

    result = q.to_query_with_params()
    assert '"age"' in result[0].query

def test_add_foreign_key_constraint_parses_referential_action_enums(sql_dialect: SQLDialect, mock_db) -> None:
    q = AlterTableQuery(sql_dialect, "posts", database=mock_db)
    q.add_foreign_key_constraint(
        "user_id", "users", "id",
        name="fk1",
        referential_actions=[
            ReferentialActionEnum.ON_DELETE_CASCADE,
            ReferentialActionEnum.ON_UPDATE_SET_NULL,
        ],
    )

    alter = q._alters[0]
    assert isinstance(alter, AddForeignKeyConstraint)
    assert alter.on_delete == "CASCADE"
    assert alter.on_update == "SET NULL"


def test_foreign_key_constraint_emits_referential_actions_in_create_table(sql_dialect: SQLDialect, mock_db) -> None:
    q = CreateTableQuery(sql_dialect, "posts", database=mock_db)
    q.integer("id")
    q.foreign_key_constraint(
        "user_id", "users", "id",
        name="fk1",
        referential_actions=[
            ReferentialActionEnum.ON_DELETE_CASCADE,
            ReferentialActionEnum.ON_UPDATE_SET_NULL,
        ],
    )
    sql = q.to_query_with_params().query

    assert "ON DELETE CASCADE" in sql
    assert "ON UPDATE SET NULL" in sql


def test_create_table_builders_produce_column_dataclass_instances(sql_dialect: SQLDialect, mock_db) -> None:
    """Every ColumnsDefinitionMixin builder method must append a `Column`
    dataclass to `_columns`, not an untyped dict -- this is the crux of the
    dict-to-dataclass migration."""
    q = CreateTableQuery(sql_dialect, "widgets", database=mock_db)
    q.integer("id")
    q.string("name")
    q.boolean("active")
    q.identity("pk")

    assert all(isinstance(col, Column) for col in q._columns)


def test_create_table_constraint_builders_produce_constraint_dataclass_instances(
    sql_dialect: SQLDialect, mock_db
) -> None:
    """unique_constraint()/foreign_key_constraint()/constraint() must append
    ConstraintABC dataclasses, discriminated by class rather than a "type"
    string key."""
    q = CreateTableQuery(sql_dialect, "widgets", database=mock_db)
    q.unique_constraint(["name"])
    q.foreign_key_constraint("owner_id", "users", "id")
    q.constraint("CHECK (id > 0)")

    assert isinstance(q._constraints[0], UniqueConstraint)
    assert isinstance(q._constraints[1], ForeignKeyConstraint)
    assert isinstance(q._constraints[2], RawConstraint)
    assert all(isinstance(c, ConstraintABC) for c in q._constraints)


def test_alter_table_builders_produce_alter_dataclass_instances(sql_dialect: SQLDialect, mock_db) -> None:
    """Every AltersMixin builder method must append the matching AlterABC
    dataclass -- add_column -> AddColumn, alter_column -> AlterColumn,
    rename_column -> RenameColumn, drop_column -> DropColumn,
    add_primary_keys -> AddPrimaryKeys, add_unique_constraint ->
    AddUniqueConstraint, add_foreign_key_constraint ->
    AddForeignKeyConstraint, drop_constraint -> DropConstraint,
    alter -> RawAlter."""
    q = AlterTableQuery(sql_dialect, "widgets", database=mock_db)
    q.add_column("email", TypeEnum.STRING)
    q.alter_column("age", "TYPE BIGINT")
    q.rename_column("old", "new")
    q.drop_column("temp")
    q.add_primary_keys("id")
    q.add_unique_constraint(["email"])
    q.add_foreign_key_constraint("owner_id", "users", "id")
    q.drop_constraint("uq_email")
    q.alter("SOME RAW SQL")

    expected_types = [
        AddColumn, AlterColumn, RenameColumn, DropColumn, AddPrimaryKeys,
        AddUniqueConstraint, AddForeignKeyConstraint, DropConstraint, RawAlter,
    ]
    assert [type(alter) for alter in q._alters] == expected_types
    assert all(isinstance(alter, AlterABC) for alter in q._alters)


def test_unknown_alter_type_raises_clear_error(sql_dialect: SQLDialect) -> None:
    """An AlterABC subtype the dialect doesn't recognize must raise a clear
    QueryError from `_build_alter`, not silently render a bare
    'ALTER TABLE t' with the operation dropped."""

    @dataclass
    class _UnknownAlter(AlterABC):
        pass

    with pytest.raises(QueryError, match="Unsupported alter type"):
        sql_dialect.alter_table(table="t", alters=[_UnknownAlter()])


def test_unknown_constraint_type_raises_clear_error(sql_dialect: SQLDialect) -> None:
    """A ConstraintABC subtype the dialect doesn't recognize must raise a
    clear QueryError from `_build_constraint`, not silently emit an empty
    constraint clause."""

    @dataclass
    class _UnknownConstraint(ConstraintABC):
        pass

    with pytest.raises(QueryError, match="Unsupported constraint type"):
        sql_dialect.create_table(
            if_not_exists=False,
            table="t",
            columns=[Column(name="id", type=TypeEnum.INT)],
            primary_keys=None,
            constraints=[_UnknownConstraint()],
        )
