"""Regression tests for the MySQL/PostgreSQL/SQLite dialect subclasses,
covering behavioral gaps found while re-porting them to delegate via
super()/the base dialect's seams instead of reimplementing shared logic.

Each test here maps to a specific PHP source of truth cited in its
docstring -- see Database/Dialects/{MySQLDialect,PgSQLDialect,
SQLiteDialect}.php.
"""
from __future__ import annotations

from flowmaticdb.dialects import MySQLDialect, PostgresqlDialect, SQLiteDialect
from flowmaticdb.query import Condition
from flowmaticdb.query.ddl import Column, DropColumn, ForeignKeyConstraint, UniqueConstraint
from flowmaticdb.query.enums import ConditionEnum, TypeEnum


def test_mysql_cast_types_used_for_equals_cast(mysql_dialect: MySQLDialect) -> None:
    """MySQLDialect::CAST_TYPES remaps bool/int/float/string to
    UNSIGNED/SIGNED/DECIMAL/CHAR instead of the generic SQL type names."""
    cond = Condition(condition=ConditionEnum.EQUALS, identifier="n", value=42, cast=True)
    parts: list[str] = []
    params: list[object] = []
    mysql_dialect._build_condition(parts, params, cond)
    result = "".join(parts)
    assert "AS SIGNED)" in result

    cond_str = Condition(condition=ConditionEnum.EQUALS, identifier="s", value="x", cast=True)
    parts2: list[str] = []
    params2: list[object] = []
    mysql_dialect._build_condition(parts2, params2, cond_str)
    assert "AS CHAR)" in "".join(parts2)


def test_mysql_default_value_escaping_uses_escape_chars(mysql_dialect: MySQLDialect) -> None:
    """A string DEFAULT goes through escape_string(), which must wrap in '"'
    and backslash-escape control characters per MySQLDialect::ESCAPE_CHARS,
    not the hand-rolled two-char .replace() chain the old override used."""
    col_def = mysql_dialect._build_column(
        Column(name="note", type=TypeEnum.STRING, default="a\nb")
    )
    assert col_def == '`note` VARCHAR(255) DEFAULT "a\\nb"'


def test_mysql_datetime_format_includes_microseconds(mysql_dialect: MySQLDialect) -> None:
    """MySQLDialect::DATETIME_FORMAT is 'Y-m-d H:i:s.u' (with fractional
    seconds) -- the old port's format string omitted the .%f part."""
    from datetime import UTC, datetime

    dt = datetime(2024, 1, 2, 3, 4, 5, 123456, tzinfo=UTC)
    assert mysql_dialect.cast_datetime(dt) == "2024-01-02 03:04:05.123456"

def test_pg_identity_column_modern_version() -> None:
    """PgSQLDialect::buildColumn: PostgreSQL >= 17 uses GENERATED BY DEFAULT
    AS IDENTITY directly (delegating to the base column builder unchanged)."""
    pg = PostgresqlDialect(version="17")
    col_def = pg._build_column(
        Column(name="id", type=TypeEnum.INT, auto_increment=True, not_null=True)
    )
    assert "GENERATED BY DEFAULT AS IDENTITY" in col_def
    assert "SERIAL" not in col_def.upper()


def test_pg_identity_column_falls_back_to_serial_before_pg17() -> None:
    """PgSQLDialect::buildColumn: below PostgreSQL 17, an identity column
    swaps its type for SERIAL/BIGSERIAL instead."""
    pg = PostgresqlDialect(version="16")
    assert pg.generated_by_default_as_identity is False

    int_col = pg._build_column(Column(name="id", type="INTEGER", auto_increment=True))
    assert int_col == '"id" SERIAL'

    bigint_col = pg._build_column(Column(name="id", type="bigint", auto_increment=True))
    assert bigint_col == '"id" bigserial'


def test_pg_use_serials_option_forces_serial_even_on_pg17() -> None:
    pg = PostgresqlDialect(version="17", options={"use_serials": True})
    col_def = pg._build_column(Column(name="id", type="INTEGER", auto_increment=True))
    assert col_def == '"id" SERIAL'


def test_pg_generated_by_default_as_identity_gate() -> None:
    """PgSQLDialect::generatedByDefaultAsIdentity() gates on PostgreSQL 17+
    (see the README's documented PostgreSQL support matrix), not 10."""
    assert PostgresqlDialect(version="16").generated_by_default_as_identity is False
    assert PostgresqlDialect(version="17").generated_by_default_as_identity is True


def test_pg_regex_uses_function_form_by_default(pg_dialect: PostgresqlDialect) -> None:
    """PgSQLDialect::buildConditionRegex: PostgreSQL >= 15 uses the shared
    regexp_like() function form."""
    cond = Condition(condition=ConditionEnum.REGEX, identifier="email", value="^a@b$")
    parts: list[str] = []
    params: list[object] = []
    pg_dialect._build_condition(parts, params, cond)
    assert "".join(parts).startswith('regexp_like("email", ')


def test_pg_regex_uses_tilde_operator_before_pg15() -> None:
    pg = PostgresqlDialect(version="12")
    cond = Condition(condition=ConditionEnum.REGEX, identifier="email", value="^a@b$")
    parts: list[str] = []
    params: list[object] = []
    pg._build_condition(parts, params, cond)
    assert "".join(parts) == '"email" ~ ?'

    not_cond = Condition(condition=ConditionEnum.NOT_REGEX, identifier="email", value="^a@b$")
    parts2: list[str] = []
    params2: list[object] = []
    pg._build_condition(parts2, params2, not_cond)
    assert "".join(parts2) == '"email" !~ ?'


def test_pg_use_tilde_regex_option_forces_operator_form(pg_dialect: PostgresqlDialect) -> None:
    pg = PostgresqlDialect(version="16", options={"use_tilde_regex": True})
    cond = Condition(condition=ConditionEnum.REGEX, identifier="email", value="^a@b$")
    parts: list[str] = []
    params: list[object] = []
    pg._build_condition(parts, params, cond)
    assert "".join(parts) == '"email" ~ ?'


def test_pg_escape_string_uses_escape_chars(pg_dialect: PostgresqlDialect) -> None:
    """PgSQLDialect doesn't override escapeString -- it configures
    ESCAPE_CHARS on the shared base implementation instead."""
    assert pg_dialect.escape_string("it's") == "'it''s'"
    assert pg_dialect.escape_string("back\\slash") == "'back\\\\slash'"
    assert pg_dialect.escape_string("line1\nline2\ttab") == "'line1\\nline2\\ttab'"
    assert pg_dialect.escape_string("nul\x00byte") == "'nulbyte'"


def test_pg_returning_and_on_conflict_not_overridden_beyond_gating(pg_dialect: PostgresqlDialect) -> None:
    """PgSQLDialect never overrides buildReturning; it must fully inherit
    the base's self.returning gate (an empty-but-non-None returning list
    still renders RETURNING *)."""
    qwp = pg_dialect.insert(
        table="users", values=[{"name": "a"}], on_conflict=None, returning=[], last_insert_id=None
    )
    assert "RETURNING *" in qwp.query

def test_sqlite_like_is_case_sensitive_glob_by_default(sqlite_dialect: SQLiteDialect) -> None:
    """SQLiteDialect::buildConditionLike: native SQLite LIKE is
    case-insensitive for ASCII, so the (case-sensitive) default LIKE
    condition is translated to GLOB instead."""
    cond = Condition(condition=ConditionEnum.LIKE, identifier="name", value="foo%bar_baz")
    parts: list[str] = []
    params: list[object] = []
    sqlite_dialect._build_condition(parts, params, cond)
    assert "".join(parts) == '"name" GLOB ?'
    assert params == ["foo*bar?baz"]


def test_sqlite_like_case_insensitive_uses_native_like(sqlite_dialect: SQLiteDialect) -> None:
    cond = Condition(
        condition=ConditionEnum.LIKE, identifier="name", value="foo%bar", case_insensitive=True
    )
    parts: list[str] = []
    params: list[object] = []
    sqlite_dialect._build_condition(parts, params, cond)
    assert "".join(parts) == '"name" LIKE ?'
    assert params == ["foo%bar"]


def test_sqlite_glob_condition_case_insensitive_wraps_lower(sqlite_dialect: SQLiteDialect) -> None:
    cond = Condition(
        condition=ConditionEnum.GLOB, identifier="name", value="foo*", case_insensitive=True
    )
    parts: list[str] = []
    params: list[object] = []
    sqlite_dialect._build_condition(parts, params, cond)
    assert "".join(parts) == 'lower("name") GLOB lower(?)'


def test_sqlite_regex_uses_function_form_by_default(sqlite_dialect: SQLiteDialect) -> None:
    """SQLiteDialect::buildConditionRegex: the default is the shared
    regexp_like() function form, not a REGEXP operator -- the old code had
    dead branching that always emitted the operator form."""
    cond = Condition(condition=ConditionEnum.REGEX, identifier="email", value="^a@b$")
    parts: list[str] = []
    params: list[object] = []
    sqlite_dialect._build_condition(parts, params, cond)
    assert "".join(parts).startswith('regexp_like("email", ')


def test_sqlite_regex_operator_form_via_option(sqlite_dialect: SQLiteDialect) -> None:
    sqlite_opt = SQLiteDialect(options={"use_regexp": True})
    cond = Condition(condition=ConditionEnum.REGEX, identifier="email", value="^a@b$")
    parts: list[str] = []
    params: list[object] = []
    sqlite_opt._build_condition(parts, params, cond)
    assert "".join(parts) == '"email" REGEXP ?'


def test_sqlite_unique_constraint_strips_name(sqlite_dialect: SQLiteDialect) -> None:
    """SQLiteDialect::buildUniqueConstraint/buildForeignKeyConstraint always
    strip the constraint name before delegating to the shared builder."""
    sql = sqlite_dialect._build_constraint(
        UniqueConstraint(columns=["email"], name="uq_email")
    )
    assert sql == 'UNIQUE ("email")'


def test_sqlite_foreign_key_constraint_strips_name(sqlite_dialect: SQLiteDialect) -> None:
    sql = sqlite_dialect._build_constraint(
        ForeignKeyConstraint(
            columns=["user_id"],
            ref_table="users",
            ref_columns=["id"],
            name="fk_user",
        )
    )
    assert sql == 'FOREIGN KEY ("user_id") REFERENCES "users" ("id")'


def test_sqlite_create_table_excludes_auto_increment_column_from_primary_key(
    sqlite_dialect: SQLiteDialect,
) -> None:
    """SQLiteDialect::createTable removes an auto-increment column's own
    name from the primary_keys list before delegating, since its inline
    'INTEGER PRIMARY KEY AUTOINCREMENT' already declares the table's sole
    primary key -- listing it again would produce a second, invalid
    PRIMARY KEY (...) clause."""
    qwp = sqlite_dialect.create_table(
        if_not_exists=False,
        table="users",
        columns=[Column(name="id", type=TypeEnum.INT, auto_increment=True)],
        primary_keys=["id"],
    )
    assert qwp.query.count("PRIMARY KEY") == 1
    assert "INTEGER PRIMARY KEY AUTOINCREMENT" in qwp.query


def test_sqlite_auto_increment_ignores_declared_type(sqlite_dialect: SQLiteDialect) -> None:
    """SQLiteDialect::buildColumn forces INTEGER PRIMARY KEY AUTOINCREMENT
    unconditionally for an identity column, regardless of the declared
    type -- the old code only did this when the resolved type happened to
    already be 'INTEGER'."""
    col_def = sqlite_dialect._build_column(
        Column(name="id", type="BIGINT", auto_increment=True)
    )
    assert col_def == '"id" INTEGER PRIMARY KEY AUTOINCREMENT'


def test_sqlite_drop_column_has_no_version_gate() -> None:
    """SQLiteDialect has no buildAlterTableDropColumn override in PHP --
    DROP COLUMN is always emitted regardless of version (unlike
    RENAME COLUMN, which is explicitly version-gated)."""
    old_sqlite = SQLiteDialect(version="3.1.0")
    qwp = old_sqlite._build_alter("t", DropColumn(column="c"))
    assert qwp.query == 'ALTER TABLE "t" DROP COLUMN "c"'
